# Welcome to Jekyll!

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
relative_permalinks: false

# About/contact
author:
  name: Thomas Huijskens
  email: thomas_huijskens@hotmail.com

# Site settings
title: Thomas Huijskens
description: > # this means to ignore newlines until "baseurl:"
  This is a placeholder description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thuijskens.github.io" # the base hostname & protocol for your site
github_username:  thuijskens
paginate: 5

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

# Custom vars
version: 1.0.0
